channels:
- conda-forge
- bioconda
dependencies:
- bash
- r
- perl
- parallel
- gawk
- sed
- grep
- bc
- git
- coreutils
- wget
- barrnap
- bedtools
- exonerate
- glpk
- hmmer
- blast
- bioconda::libsbml 
- r-data.table
- r-stringr
- r-stringi
- r-getopt
- r-doParallel
- r-foreach
- r-r.utils
- r-sybil
- r-biocmanager
- bioconductor-biostrings
- r-jsonlite
- r-renv