name: mapping-bowtie-env

channels:
  - conda-forge
  - bioconda
  - hcc
  - agbiome

dependencies:
  - python=3.9.7
  - openjdk=11.0.9.1
  - perl=5.32.1
  - samtools>=1.10
  - picard=2.26.2
  - bwa=0.7.17
  - bedtools
  - metabat2
  - blast
  - bbmap
  - bbtools
  - muscle=3.8.1551
  - bowtie2