name: phylogenies-env

channels:
 - conda-forge
 - bioconda

dependencies:
 - python>=3.6
 - biopython
 - iqtree
 - mafft
 - openjdk<=17.0.2
 # prokka needs openjdk version to be limited
 # (see:https://github.com/tseemann/prokka/issues/557)
 - prokka
 - orthofinder
 - bioconductor-biostrings
 - prodigal
 - diamond
 - mcl
 - fastme
 - fasttree
 - mmseqs2
