name: scripts-env

channels:
  - conda-forge
  - bioconda
  - hcc
  - plotly

dependencies:
  - python>=3.6
  - biopython
  - numpy
  - pandas
  - time
  - tabulate
  - panel
  - pyfastx>=0.4.8
  - plotly
  - matplotlib
  - basemap
  - seaborn
  - AdjustText
  # - bcbio-gff